site_name: 技术传播百态说
theme:
  name: material
  language: zh
  logo: assets/logo/logo_v3.svg
  favicon: assets/logo/favicon.ico
  palette:
    # Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: custom
      accent: custom
    # Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: custom
      accent: custom
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.path
    - toc.follow
  custom_dir: overrides

extra_css:
  - stylesheets/palette.css
  - stylesheets/page.css
  - stylesheets/nav.css
  - stylesheets/header.css
  - stylesheets/footer.css

extra:
  homepage: https://www.tcblabber.cn/
  doc_title: "Pilot Training Manual for the Mitchell Bomber B-25"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wongyah/pilot_training_manual_for_mitchell_bomber
      name: "Pilot Training Manual for the Mitchell Bomber B-25"
    - icon: simple/wechat
      link: "https://mp.weixin.qq.com/s?__biz=MzA5NzU4ODAwOQ==&mid=2247487464&idx=1&sn=c57c1b993dcb2c166d88bc2c0d414a10&chksm=909fc9aea7e840b874ebe3e37d0e2a58de7c4c4c5e18f1355b1a4be6378b5752c571c4aeddd4&token=587590048&lang=zh_CN#rd"
      name: "微信公众号@技术传播百态说"
    - icon: simple/zhihu
      link: "https://www.zhihu.com/column/c_1548252009672929280"
      name: "知乎专栏@技术传播百态说"
    - icon: material/email
      link: "mailto:wongyah@126.com?subject=Markdown%20Syntax%20Hub"
      name: "我的邮箱"

copyright: "&copy; 2025 王烨."

nav:
  - Introduction:
    - introduction/index.md
    - introduction/history_of_the_mitchell_bomber.md
    - introduction/duties_and_responsibilities_of_the_airplane_commander.md
    - introduction/practical_questions.md
    - introduction/the_copilot.md
    - introduction/the_bombardier_navigator.md
    - introduction/radio_operator.md
    - introduction/the_engineer.md
    - introduction/the_gunners.md
    - introduction/rules_to_be_enforced_on_every_flight.md
    - introduction/general_description.md
  - Location of controls:
    - location-of-controls/bombardiers_compartment_left_side.md
    - location-of-controls/pilots_compartment_general_forward_view.md
    - location-of-controls/pilots_switch_panel_and_control_pedestal_panel.md
    - location-of-controls/pilots_compartment_left_side.md
    - location-of-controls/pilots_compartment_right_side.md
    - location-of-controls/hydraulic_hand_pump_and_emergency_air_brake_control.md
    - location-of-controls/navigators_compartment_forward_view.md
    - location-of-controls/radio_operators_compartment_forward_view.md
    - location-of-controls/radio_operators_compartment_left_side.md

markdown_extensions:
  - nl2br
  - abbr
  - footnotes
  - def_list
  - attr_list
  - admonition
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
      auto_title: true
  - pymdownx.blocks.html
  - pymdownx.snippets:
      base_path: snippets

